baseURL: 'https://sneddy.github.io'
languageCode: "en-us"
title: "Anuar Aimoldin"
theme: "PaperMod"

menu:
  main:
    - identifier: "resume"
      name: "Resume"
      url: "/resume/"
      weight: 20
    - identifier: "public_speaking"
      name: "Public Speaking"
      url: "/public_speaking/"
      weight: 20
    - identifier: "posts"
      name: "Blog"
      url: "/posts/"
      weight: 30


params:
  customCSS: ["css/custom.css"]
  homeInfoParams:
    Title: "Welcome to my blog!"
    Content: "{{< homecontent >}}"
  

  socialIcons:
    - name: "github"
      url: "https://github.com/sneddy"
    - name: "linkedin"
      url: "https://linkedin.com/in/anuar-aimoldin"
    - name: "mail"
      url: "mailto:aimoldin@gmail.com"


  # Show params
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter"]
  ShowReadingTime: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: true